# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('roll_number', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=32)),
                ('fathers_name', models.CharField(max_length=32)),
                ('mothers_name', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=32)),
                ('nationality', models.CharField(max_length=32)),
            ],
        ),
    ]
