# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0002_personaldetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetail',
            old_name='fathers_name',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='personaldetail',
            old_name='mothers_name',
            new_name='mother_name',
        ),
    ]
