# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0003_auto_20160404_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissiondetail',
            name='validation_comments',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
