# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0004_admissiondetail_validation_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissiondetail',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 4, 5, 14, 19, 59, 731631, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
