# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0005_admissiondetail_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_number', models.CharField(max_length=32)),
                ('education_type', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('board', models.CharField(max_length=32)),
                ('school', models.CharField(max_length=32)),
                ('year_of_graduation', models.DateField()),
            ],
        ),
    ]
