# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0006_educationdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetails',
            name='year_of_graduation',
            field=models.IntegerField(),
        ),
    ]
