# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0008_addressdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressDetails',
        ),
    ]
