# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0009_delete_addressdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_number', models.CharField(max_length=32)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('address3', models.CharField(max_length=100)),
                ('state', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
