# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0011_auto_20160406_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
