# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0013_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramApplied',
            fields=[
                ('program_applied_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_number', models.CharField(max_length=32)),
                ('course_id', models.IntegerField()),
                ('exam_name_id', models.IntegerField()),
                ('exam_subject_id', models.IntegerField()),
                ('marks_scored', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
