# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0015_auto_20160406_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='email_id',
            field=models.CharField(default='Ankur.gupta@iiitb.org', max_length=32),
        ),
    ]
