# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0016_personaldetail_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRef',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_desc', models.CharField(max_length=32)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRef',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_desc', models.CharField(max_length=32)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamRef',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_desc', models.CharField(max_length=32)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubjectRef',
            fields=[
                ('exam_subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_subject_desc', models.CharField(max_length=32)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramRef',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_desc', models.CharField(max_length=32)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateRef',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_desc', models.CharField(max_length=32)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='programapplied',
            name='program_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
