# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0017_auto_20160406_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDetails',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_number', models.CharField(max_length=32)),
                ('upload_type_id', models.IntegerField()),
                ('upload_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadTypeRef',
            fields=[
                ('upload_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_type_desc', models.CharField(max_length=32)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
