# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0019_auto_20160407_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationRef',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('education_name', models.CharField(max_length=32)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostApplied',
            fields=[
                ('post_applied_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_number', models.CharField(max_length=32)),
                ('post', models.IntegerField(choices=[(1, 'Software Engineer'), (2, 'Data Analyst'), (3, 'Software Developer'), (4, 'IT')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PostRef',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_desc', models.CharField(max_length=32)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='educationdetails',
            old_name='board',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='educationdetails',
            old_name='percentage',
            new_name='graduation_percentage',
        ),
        migrations.RenameField(
            model_name='educationdetails',
            old_name='school',
            new_name='high_school',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='address_id',
            new_name='work_id',
        ),
        migrations.RemoveField(
            model_name='educationdetails',
            name='education_type',
        ),
        migrations.AddField(
            model_name='educationdetails',
            name='high_school_board',
            field=models.CharField(default='cbse', max_length=32),
        ),
        migrations.AddField(
            model_name='educationdetails',
            name='high_school_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationdetails',
            name='intermediate_board',
            field=models.CharField(default='cbse', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationdetails',
            name='intermediate_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationdetails',
            name='intermediate_school',
            field=models.CharField(default='abc', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationdetails',
            name='university',
            field=models.CharField(default='abc', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationdetails',
            name='year_of_passing_10th',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='educationdetails',
            name='year_of_passing_12th',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='state',
            field=models.IntegerField(choices=[(1, 'Andhra Pradesh'), (2, 'Arunachal Pradesh'), (3, 'Assam'), (4, 'Bihar'), (5, 'Chattisgarh')], default=1),
        ),
        migrations.AlterField(
            model_name='admissiondetail',
            name='status_of_request',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Valid'), (3, 'Incomplete'), (4, 'Invalid')], default=1),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='year_of_graduation',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='category_id',
            field=models.IntegerField(choices=[(1, 'Gen'), (2, 'SC/ST'), (3, 'OBC')], default=1),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='phone_number',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='programapplied',
            name='course_id',
            field=models.IntegerField(choices=[(1, 'IT'), (2, 'ESD')], default=1),
        ),
        migrations.AlterField(
            model_name='programapplied',
            name='exam_name_id',
            field=models.IntegerField(choices=[(1, 'GATE'), (2, 'GRE'), (3, 'JEE')], default=1),
        ),
        migrations.AlterField(
            model_name='programapplied',
            name='exam_subject_id',
            field=models.IntegerField(choices=[(1, 'CS/IT'), (2, 'ECE')], default=1),
        ),
        migrations.AlterField(
            model_name='programapplied',
            name='program_id',
            field=models.IntegerField(choices=[(1, 'M.Tech'), (2, 'Integrated M.Tech'), (3, 'M.Sc Digital Society'), (4, 'MS'), (5, 'PHD')], default=1),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_year',
            field=models.IntegerField(default=2016),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_year',
            field=models.IntegerField(default=2000),
        ),
    ]
