# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0020_auto_20160410_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='current_address_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmodule.AddressDetails'),
        ),
    ]
