# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0021_auto_20160410_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='current_address_id',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='residential_address_id',
        ),
    ]
