# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0023_auto_20160410_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressRef',
            fields=[
                ('addRef_id', models.AutoField(primary_key=True, serialize=False)),
                ('add_type_id', models.PositiveSmallIntegerField()),
                ('add_desc', models.CharField(max_length=32)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminReference',
            fields=[
                ('reference_id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('offer_id', models.PositiveSmallIntegerField(choices=[(1, 'admission'), (2, 'job')], default='admission')),
                ('created_by', models.CharField(max_length=32)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('form_submission_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GenderRef',
            fields=[
                ('gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender_desc', models.CharField(max_length=32)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoFiles',
            fields=[
                ('photoFile_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_number', models.CharField(max_length=32, unique=True)),
                ('photograph_file', models.FileField(null=True, upload_to=b'/home/anushree/django/testdjango/media')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureFiles',
            fields=[
                ('sigFile_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_number', models.CharField(max_length=32, unique=True)),
                ('signature_file', models.FileField(null=True, upload_to=b'/home/anushree/django/testdjango/media')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_number', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='XthMarksheets',
            fields=[
                ('xmFile_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_number', models.CharField(max_length=32, unique=True)),
                ('xth_marksheet', models.FileField(null=True, upload_to=b'/home/anushree/django/testdjango/media')),
            ],
        ),
        migrations.RenameField(
            model_name='educationdetails',
            old_name='college',
            new_name='board_university',
        ),
        migrations.RenameField(
            model_name='educationdetails',
            old_name='high_school',
            new_name='institute',
        ),
        migrations.RenameField(
            model_name='educationdetails',
            old_name='graduation_percentage',
            new_name='percentage',
        ),
        migrations.RenameField(
            model_name='educationdetails',
            old_name='year_of_graduation',
            new_name='year_of_passing',
        ),
        migrations.RenameField(
            model_name='educationref',
            old_name='education_name',
            new_name='education_desc',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='work_id',
            new_name='workEx_id',
        ),
        migrations.RemoveField(
            model_name='educationdetails',
            name='high_school_board',
        ),
        migrations.RemoveField(
            model_name='educationdetails',
            name='high_school_percentage',
        ),
        migrations.RemoveField(
            model_name='educationdetails',
            name='intermediate_board',
        ),
        migrations.RemoveField(
            model_name='educationdetails',
            name='intermediate_percentage',
        ),
        migrations.RemoveField(
            model_name='educationdetails',
            name='intermediate_school',
        ),
        migrations.RemoveField(
            model_name='educationdetails',
            name='university',
        ),
        migrations.RemoveField(
            model_name='educationdetails',
            name='year_of_passing_10th',
        ),
        migrations.RemoveField(
            model_name='educationdetails',
            name='year_of_passing_12th',
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='address_type',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='educationdetails',
            name='education_type',
            field=models.IntegerField(choices=[(1, 'Xth'), (2, 'XIIth'), (3, 'Graduation')], default=1),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='state',
            field=models.IntegerField(choices=[(0, '---'), (1, 'Andhra Pradesh'), (2, 'Arunachal Pradesh'), (3, 'Assam'), (4, 'Bihar'), (5, 'Chattisgarh'), (6, 'Karnataka')]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='category_id',
            field=models.IntegerField(choices=[(1, 'Gen'), (2, 'SC/ST'), (3, 'OBC')]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')]),
        ),
        migrations.AlterField(
            model_name='uploaddetails',
            name='upload_type_id',
            field=models.ForeignKey(choices=[(1, 'Photograph'), (2, 'Signature'), (3, 'Xth Marksheet'), (4, 'Xth Certificate'), (5, 'XIIth Marksheet'), (6, 'XIIth Certificate'), (7, 'Graduation Marksheet'), (8, 'Graduation Certificate'), (9, 'Gate Score Card'), (10, 'Salary Slip')], on_delete=django.db.models.deletion.CASCADE, to='staffmodule.UploadTypeRef'),
        ),
    ]
