# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0028_auto_20160423_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaddetails',
            old_name='upload_type_id',
            new_name='upload_type',
        ),
    ]
