# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0029_auto_20160423_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photofiles',
            name='photograph_file',
            field=models.FileField(null=True, upload_to=b'/home/anushree/django/SE-Project/media'),
        ),
        migrations.AlterField(
            model_name='signaturefiles',
            name='signature_file',
            field=models.FileField(null=True, upload_to=b'/home/anushree/django/SE-Project/media'),
        ),
        migrations.AlterField(
            model_name='xthmarksheets',
            name='xth_marksheet',
            field=models.FileField(null=True, upload_to=b'/home/anushree/django/SE-Project/media'),
        ),
    ]
