# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmodule', '0030_auto_20160423_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminreference',
            name='offer_id',
        ),
        migrations.AddField(
            model_name='adminreference',
            name='form_template',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admission'), (2, 'Job')], default=1),
        ),
    ]
