# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='12345678', max_length=20)),
                ('confirmPassword', models.CharField(default='12345678', max_length=20)),
                ('role', models.CharField(choices=[('Admin', 'Administrator'), ('Staff', 'Staff'), ('User', 'Candidate')], default=1, max_length=5)),
                ('approve', models.CharField(default='3', max_length=1)),
            ],
        ),
    ]
