# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_matchref'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='match',
            field=models.CharField(default='Pending', max_length=10),
            preserve_default=False,
        ),
    ]
